# Generated by Django 6.0.1 on 2026-02-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('source', 'external_event_id')},
        ),
    ]
