# Generated by Django 6.0.1 on 2026-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='received', max_length=20),
        ),
    ]
