# Generated by Django 6.0.1 on 2026-02-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_event_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('unsupported', 'Unsupported'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20),
        ),
    ]
