# Generated by Django 6.0.1 on 2026-02-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_processed_at_event_processing_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='processed_at',
            new_name='processing_started_at',
        ),
    ]
