# Generated by Django 6.0.1 on 2026-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_processed_at_event_processing_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='normalized_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
