# Generated by Django 6.0.1 on 2026-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_normalized_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
